# Generated by Django 5.1 on 2024-08-16 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookrecommendation',
            name='recommended_by',
        ),
    ]
