# Generated by Django 5.1 on 2024-08-16 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_remove_bookrecommendation_recommended_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='publication_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bookrecommendation',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
