# Generated by Django 5.1 on 2024-08-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_bookrecommendation_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
