# Generated by Django 5.1 on 2024-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_alter_bookrecommendation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
