# Generated by Django 5.1 on 2024-08-16 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_alter_bookrecommendation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookrecommendation',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
