# Generated by Django 5.1 on 2024-08-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_alter_bookrecommendation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrecommendation',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
